### ISSUE TITLE
unable to confirm SSL

### ISSUE THREAD

**Issue by random-robbie** [integrity-sa/burpcollaborator-docker#5]
i have my NS at cloudflare and then point NS1 and NS2 at my vps and wildcard A name to my ip.

everytime it trys to grab the SSL i get.

```
DNSMASQ CMD:
/usr/sbin/dnsmasq -q --dns-rr=ssrfdns.fun,257,000569737375656C657473656E63727970742E6F7267 --txt-record=_acme-challenge.ssrfdns.fun,"NbzpeF7hngULgzUr8N1O9JZ5UvNzWFInhK4m3EQJbIc" --txt-record=_acme-challenge.ssrfdns.fun,"IOTRix3LnA4O60dMU2vkabM1tDqLX44K8UjzlPAWUjQ" --no-resolv --port=53
Waiting 10 seconds for DNS changes to propagate
NbzpeF7hngULgzUr8N1O9JZ5UvNzWFInhK4m3EQJbIc"Waiting for verification...
Cleaning up challenges
Failed authorization procedure. ssrfdns.fun (dns-01): urn:ietf:params:acme:error:unauthorized :: The client lacks sufficient authorization :: No TXT record found at _acme-challenge.ssrfdns.fun, ssrfdns.fun (dns-01): urn:ietf:params:acme:error:unauthorized :: The client lacks sufficient authorization :: No TXT record found at _acme-challenge.ssrfdns.fun
```

is it possible to add a new feature where if you provide something like -cf switch it updates a text record @ cloudflare via the API?

i know this txt record is being added to the dnsmasq but it does not seem to work for me.

**Comment by morisson** [comment]
Hi Robbie,

You'll have to delegate a subdomain to your VPS, such as burp.ssrfdns.fun, since burp collaborator will have to be the authoritative NS for the domain/subdomain you're using.

Other option would be to delegate the whole domain to the VPS IP address, but since most (if not all) registrars will require 2 nameservers, you'll have a harder time doing that.

Either way, it is not possible to add the TXT records to cloudflare directly, it won't work.
